version: '3'
services:
  db_mysql_new:
    image: mysql:5.7
    container_name: db_mysql_new
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: users_db
    volumes:
      - ./db_poblada_mysql/mysql:/var/lib/mysql
    ports:
      - "3307:3306"